### ISSUE TITLE
Feat: Adding Colour Scheme to Organisational Units

### ISSUE THREAD

**Issue by m-b-e** [technologiestiftung/organigramming-berlin#13]
Add new Feature:
Design, give users the ability to assign different colours to individual organisational units/boxes. Screenshot below taken from German Federal Ministry of the Interior
<img width="324" alt="Bildschirmfoto 2022-12-01 um 11 12 19" src="https://user-images.githubusercontent.com/36029603/205026372-d047b0a6-32ee-4752-bb7d-17688ed634f6.png">

**Comment by hanshack** [comment]
Some issues we should consider before implementation: 
- Do we want to limit the colors (by having e.g. a dropdown) or have a color picker (or/and a text input for hex values)?
- Do we want the change the body color or the header color too?
- Is the color UI always visible or does it appear when the user selects a 'custom' style from the style dropdown?
- does the text color change to white if the background it too light?

**Comment by hejjoe** [comment]
I think these colors are just showing the location of the units in a not very accessible way. Maybe there are better ways to show, which unit is operating from which city? Maybe the location of the unit could be displayed differently? Maybe these kind of color codes are not the best way to display certain information for screenreaders?

**Comment by hanshack** [comment]
Idea: Add a field that asks the user when the color means
