### ISSUE TITLE
Restrict text width in boxes with line break

### ISSUE THREAD

**Issue by m-b-e** [technologiestiftung/organigramming-berlin#38]
When adding long titles or descriptions for divisions/organisations, text expands past the borders of the text box, or disappears within the header

![Bildschirmfoto 2023-02-14 um 15 27 13](https://user-images.githubusercontent.com/36029603/218767610-0e25b543-c3f3-47c0-9bf8-a88fae7cba88.png)
![Bildschirmfoto 2023-02-14 um 15 26 33](https://user-images.githubusercontent.com/36029603/218767614-bd06b03c-29a8-48fc-b79a-c5de5fa85e5c.png)

**Comment by hanshack** [comment]
Fixed: https://github.com/technologiestiftung/organigramming-berlin/pull/41
